/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./rl_*/*.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#030e07",
        "primary-container": "#17251c",
        "on-primary": "#ffffff",
        "on-primary-container": "#7d8d81",
        "primary-fixed": "#d6e7d8",
        "primary-fixed-dim": "#bacbbd",
        "on-primary-fixed": "#111e16",
        "on-primary-fixed-variant": "#3b4a40",
        "inverse-primary": "#bacbbd",

        "secondary": "#516446",
        "secondary-container": "#d1e6c1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#55684a",
        "secondary-fixed": "#d4e9c4",
        "secondary-fixed-dim": "#b8cda9",
        "on-secondary-fixed": "#0f1f08",
        "on-secondary-fixed-variant": "#3a4c30",

        "tertiary": "#040e00",
        "tertiary-container": "#17260a",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7c8f69",
        "tertiary-fixed": "#d5e9be",
        "tertiary-fixed-dim": "#b9cda3",
        "on-tertiary-fixed": "#111f05",
        "on-tertiary-fixed-variant": "#3b4c2c",

        "surface": "#f7faf2",
        "surface-dim": "#d8dbd3",
        "surface-bright": "#f7faf2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f5ec",
        "surface-container": "#ecefe7",
        "surface-container-high": "#e6e9e1",
        "surface-container-highest": "#e0e4dc",
        "surface-variant": "#e0e4dc",
        "surface-tint": "#536257",

        "on-surface": "#191d18",
        "on-surface-variant": "#434844",
        "inverse-surface": "#2d312c",
        "inverse-on-surface": "#eff2ea",

        "outline": "#737873",
        "outline-variant": "#c3c8c2",

        "background": "#f7faf2",
        "on-background": "#191d18",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "sans": ["IBM Plex Sans", "sans-serif"],
        "mono": ["IBM Plex Mono", "monospace"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-xl": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "headline-xl-mobile": ["IBM Plex Sans", "sans-serif"],
        "label-xs": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "label-xs": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl-mobile": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
      },
    },
  },
  plugins: [],
}
